### ISSUE TITLE
loop creation

### ISSUE THREAD

**Issue by DevCleverton** [conversejs/converse-desktop#25] opened 2022-08-20 00:51 UTC
for me it is doing a loading loop, creating a registry, in windows

![image](https://user-images.githubusercontent.com/56972170/185722974-6bcc2c12-45f3-4185-9785-5cccd6542e9b.png)

**Comment by jcbrand** [comment] 2022-11-14 09:15
Looks like this is a duplicate of https://github.com/conversejs/converse.js/issues/1490

**Closed by jcbrand** 2022-11-14 09:15 UTC
